### ISSUE TITLE
Adding a Configuration Service

### ISSUE THREAD

**Issue by br15** [csharpschool/AspNetVideoCore#2]
Page 16. point 3. Select the ASP.NET Configuration File template.

Unfortunately at this point there is nothing in the dialog to select as the search found nothing? I've attached a screen shot of the dialog pre search.

My dev environment is: Visual Studio Community 2017 Version 15.5.6

![image](https://user-images.githubusercontent.com/7603680/36164625-d57fab52-10e4-11e8-96a7-fcbc196f11b2.png)

**Comment by csharpschool** [comment]
The name has been changed to _App Settings File_.
